// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBirtqAn-u6czK2NqPtuSyIbHHVBLtVxs0',
    appId: '1:579463191769:web:c63a3a7d6cec5aac4772c8',
    messagingSenderId: '579463191769',
    projectId: 'doctorapp-4843a',
    authDomain: 'doctorapp-4843a.firebaseapp.com',
    storageBucket: 'doctorapp-4843a.appspot.com',
    measurementId: 'G-8LGNCB5P57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn0sBcUrlMn2PTaNaRSXOsCmyNrEOndcw',
    appId: '1:579463191769:android:417d890216f7485f4772c8',
    messagingSenderId: '579463191769',
    projectId: 'doctorapp-4843a',
    storageBucket: 'doctorapp-4843a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR9b2Pdt85MH1dR-xIMvyU4rTKNnAcRXk',
    appId: '1:579463191769:ios:91d57141f974ae3b4772c8',
    messagingSenderId: '579463191769',
    projectId: 'doctorapp-4843a',
    storageBucket: 'doctorapp-4843a.appspot.com',
    iosBundleId: 'com.example.doctors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR9b2Pdt85MH1dR-xIMvyU4rTKNnAcRXk',
    appId: '1:579463191769:ios:91d57141f974ae3b4772c8',
    messagingSenderId: '579463191769',
    projectId: 'doctorapp-4843a',
    storageBucket: 'doctorapp-4843a.appspot.com',
    iosBundleId: 'com.example.doctors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBirtqAn-u6czK2NqPtuSyIbHHVBLtVxs0',
    appId: '1:579463191769:web:82f2e10cab9af3a94772c8',
    messagingSenderId: '579463191769',
    projectId: 'doctorapp-4843a',
    authDomain: 'doctorapp-4843a.firebaseapp.com',
    storageBucket: 'doctorapp-4843a.appspot.com',
    measurementId: 'G-0TE6JJH8PD',
  );
}
